name: Tests

on:
  push:
    branches: [master]

jobs:
  deploy-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run setup tests/test-1/data.json
      - run: |
          git config --global user.email "gurleenbindra1999@gmail.com"
          git config --global user.name "gurleenbindra"
          git add -A
          git commit -m "Added data.json"
      - uses: gurleenbindra/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "tests/test-1"
          healthcheck: "https://staging-experiment.herokuapp.com/"
          env_file: ".env"
        env:
          HD_CHECK: "true"
      - run: npm run test-action https://staging-experiment.herokuapp.com/

  deploy-test-2:
    runs-on: ubuntu-latest
    needs: deploy-test-1
    steps:
      - uses: actions/checkout@v2
      - run: npm run setup tests/test-2/public_html/index.html
      - run: |
          git config --global user.email "gurleenbindra1999@gmail.com"
          git config --global user.name "gurleenbindra"
          git add -A
          git commit -m "Added index.html"
      - uses: gurleenbindra/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "tests/test-2"
          buildpack: "https://github.com/heroku/heroku-buildpack-static.git"
          healthcheck: "https://staging-experiment.herokuapp.com/"
          delay: 5
      - run: npm run test-action https://staging-experiment.herokuapp.com/

  deploy-test-3:
    runs-on: ubuntu-latest
    needs: deploy-test-2
    steps:
      - uses: actions/checkout@v2
      - run: npm run setup tests/test-3/data.json
      - run: |
          git config --global user.email "gurleenbindra1999@gmail.com"
          git config --global user.name "gurleenbindra"
          git add -A
          git commit -m "Added data.json"
      - uses: gurleenbindra/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "tests/test-3"
          usedocker: true
          healthcheck: "https://staging-experiment.herokuapp.com/"
      - run: npm run test-action https://staging-experiment.herokuapp.com/

  deploy-test-4:
    runs-on: ubuntu-latest
    needs: deploy-test-3
    steps:
      - uses: actions/checkout@v2
      - run: npm run setup tests/test-4/data.json
      - run: |
          git config --global user.email "gurleenbindra1999@gmail.com"
          git config --global user.name "gurleenbindra"
          git add -A
          git commit -m "Added data.json"
      - uses: gurleenbindra/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "tests/test-4"
          healthcheck: "https://staging-experiment.herokuapp.com/health"
          checkstring: "ok"
          procfile: "web: gunicorn index:app"
      - run: npm run test-action https://staging-experiment.herokuapp.com/
